FROM fedora:33

RUN dnf update -y \
 && dnf install -y buildah podman fuse-overlayfs shadow-utils

RUN mkdir -p /home \
 && chmod a+rwx /home \
 && touch /etc/subgid /etc/subuid \
 && chmod g=u /etc/subgid /etc/subuid /etc/passwd

ENV HOME=/home
ENV USER=builder

WORKDIR $HOME

# Just keep the container running, allowing "oc rsh" access
CMD ["python3", "-m", "http.server"]
